### PR TITLE
Documentation improvements

### PR DESCRIPTION
**Pull request by praj-foss**
This will make changes to the existing docs and create new ones if needed. Using #261 as a reference I've prepared the initial checklist of possible changes. 

### Checklist
- [x] Proper use of function pointers using `ObjectReferenceManager` (See #231 and #281)
- [x] Notes about manual memory management: `MemoryManager`, allocation, deletion, etc
- [ ] List of common errors and troubleshooting
- [ ] Some Internal details, caveats, etc ?

_Have some suggestions? Comment below!_

### CODE REVIEW

**Comment by headius** [comment]
This is a nice start! Will we see more from you? Thanks for jumping in!

**Comment by praj-foss** [comment]
Hello again! I apologize for the delay, I couldn't find much time lately thanks to frequent covid.exe updates.
I'm doing some more research on memory management APIs, so we can hopefully get this PR ready by the weekend.

**Comment by headius** [comment]
No problem! We appreciate any help you're able to offer. If you feel like you've done as much as you're able to for a while, just mark this pull request as ready to merge.

**Comment by praj-foss** [comment]
@headius I'm putting this up for review. It includes additional docs on memory management and function pointer lifetime. Please have a look and let me know if any changes are needed. It addresses some points from #261 and a lot more can be added in the future.

**Comment by headius** [comment]
@praj-foss This looks pretty good at a glance, thank you!

@basshelal Looks good to merge?

**Comment by basshelal** [comment]
@headius Yeah looks good, merge!
Many thanks @praj-foss for your contribution, user documentation is something we're lacking and are slowly working on improving and this is a big help for us.

**Pull request merged**
