### PR TITLE
Add an optional enabler for @Pack annotations

### PR DESCRIPTION
**Pull request by flandr**

### CODE REVIEW

**Comment by headius** [comment]
I have a few issues with the patches as provided:

* Use of reflection in Struct constructor and for calling the enabler.

This is a code smell for me. If we need to use reflection to determine behavior, then something's up. Can we just pass in a boolean param for packing and let the generated struct classes propagate it? And for the enabler...would adding OS and CPU attributes to the Pack annotation be sufficient?

* Unrelated whitespace changes.

We'll work through issues and get this in.

/cc @henriqueesteves since he had some similar concerns

**Comment by goto1134** [comment]
Need this a lot. Are you going to include these changes?

**Comment by headius** [comment]
Let's try to get this wrapped up. Merge or close by 2.0.10.

**Comment by goto1134** [comment]
I'm not sure about the pack annotation. Don't think it is really good to use. I just made my variant with a constructor parameter. Not sure if it is better than what @henriquemotaesteves did in #46 . Will check out when later.

**Comment by headius** [comment]
Unsure if this is still a valid PR given recent work on struct alignment and nested structs. Removing from 2.1.

Feedback is requested.

**Comment by flandr** [comment]
Hi all, sorry for the slow response. I'm afraid that structure alignment in jnr-ffi is no longer relevant to my interests. Looking at #46, it looks like this feature has been sufficiently addressed. I think we should close out these pull requests.

**Comment by headius** [comment]
@flandr Thanks for the update!

**Pull request closed without merging**
