### PR TITLE
Fix tests on FreeBSD

### PR DESCRIPTION
**Pull request by beauby**
FreeBSD uses \_SYS__STDINT_H\_ as guard clause for sys/stdint.h, which is not currently checked against which leads to typedef conflicts.

### CODE REVIEW

**Comment by beauby** [comment]
Little bump on this one: as for https://github.com/jnr/jnr-ffi/pull/26, the failing tests were not because of this PR.

**Comment by headius** [comment]
Another bitrot case. I will eventually get to cleaning these up, but if you can do it sooner that would be great.

**Comment by beauby** [comment]
bump

**Comment by beauby** [comment]
Actually this has already been merged as part of https://github.com/jnr/jnr-ffi/pull/26. Closing.

**Pull request closed without merging**
