### PR TITLE
Fix stat.st_gid on FreeBSD 10 (applying pull request jnr-ffi/18) and other FreeBSD-related fixes.

### PR DESCRIPTION
**Pull request by emcrisostomo**
I'm re-submitting the changes proposed by @beauby in the [pull request 18][pr18] of the jnr-ffi repository. That pull request was never integrated and I'm suspecting the build error reported by TravisCI was not related with the push request itself.

However, the proposed change is very little and I checked that it fixes the problem (by rebuilding jnr-ffi and using it with the latest Logstash distribution).

[pr18]: https://github.com/jnr/jnr-ffi/pull/18

### CODE REVIEW

**Comment by Subito** [comment]
I tried the FreeBSD Port yesterday and it has the problem mentioned here. Is it no longer fixed in the FreeBSD Ports?

**Comment by emcrisostomo** [comment]
@Subito, which FreeBSD port are you talking about?

**Comment by iamasmith** [comment]
I believe @emcrisostomo looks after Logstash and his patches were for the ruby-jars for that port. The patch isn't available in the main jruby port for FreeBSD as far as I'm aware so it would be good if this was fixed properly so that both jruby and ruby ports work without additional patching.

**Comment by emcrisostomo** [comment]
It's correct @iamasmith, I'm maintaining the LogStash port and the patch is applied to the jars it bundles.

**Comment by Subito** [comment]
I installed sysutils/logstash, could it be a problem, that openjdk-7 was already installed from a pkg?

**Comment by emcrisostomo** [comment]
Hi @Subito,

No, it should not be a problem. In fact, the logstash port depends on java and a jdk port is required.

I had no other reports about this problem: what port version are you installing?

**Comment by Subito** [comment]
`logstash-1.4.2_1`. I just did `make deinstall clean` and `make install` again, but I keep getting the `NotImplementedError: stat.st_dev unsupported or native support failed to load`

**Comment by emcrisostomo** [comment]
Which FreeBSD version are you running?

**Comment by Subito** [comment]
10.1. Does it matter, that I try to run it in a Jail?

**Comment by emcrisostomo** [comment]
Thanks,

AFAIK it should not matter.

I have to have a look at that.

**Comment by emcrisostomo** [comment]
@Subito, I just tried installing the port on a vanilla FreeBSD 10.1 machine and I cannot replicate the problem you're hitting. However, this problem is off-topic here: please, post it in a more appropriate place (such as the [FreeBSD ports mailing list][ports]).

[ports]: http://lists.freebsd.org/mailman/listinfo/freebsd-ports

**Comment by ponchik** [comment]
Deer maintainer, what do we need to do to get this PR merged??

**Comment by headius** [comment]
Sorry for the delays...we (JRuby team) maintain these libraries, and were busy with a big release.

I'll have a look over things and get it merged. We have a round of jnr releases coming up, it seems.

**Comment by headius** [comment]
I know it was needed for mvn to build, but try to keep unrelated commits in a separate PR in the future.

Looks fine to me. Merging.

**Comment by emcrisostomo** [comment]
Thanks @headius,

You're right, I'll do it: they seemed more like cosmetic changes not deserving their own PR, but I agree with you.

**Comment by enebo** [comment]
We had planned on releasing this along with jruby 1.7.19 but we also planned on updating jffi to 1.2.8.  Final testing revealed something seriously wrong in jffi so we plan on looking at that before putting out jnr-jffi.  Having a hierarchy of deps suck so we like to get them all out and only propagate through the deps once.  Hopefully we will get to this in the next week or so.

**Comment by iamasmith** [comment]
Understood, thanks @enebo for the update

**Comment by headius** [comment]
FWIW, 1.2.8 was released recently and should be used by all upcoming JRuby and jnr-* releases.

**Comment by iamasmith** [comment]
Excellent, thanks for the update @headius, I'll test and can hopefully drop my FreeBSD workarounds on my projects :)

**Pull request merged**
