### PR TITLE
Permit Struct.Function.set() to be called from outside a Struct: #87

### PR DESCRIPTION
**Pull request by ahilananantha**
Make Struct.Function public in Struct so that a public member can
be set() from outside of Struct.

### CODE REVIEW

**Comment by ahilananantha** [comment]
This pull request contains a fix for #87

**Comment by ahilananantha** [comment]
Test on openjdk6 failed with:

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/apache/maven/wrapper/MavenWrapperMain : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
Could not find the main class: org.apache.maven.wrapper.MavenWrapperMain. Program will exit.

Is that really because of my change?

**Comment by ahilananantha** [comment]
never mind the noob question. i see the same issue in master.

**Comment by headius** [comment]
Thank you!

**Pull request merged**
