### PR TITLE
Fix returning cast to boolean 

### PR DESCRIPTION
**Pull request by zhanhb**
With return to boolean, the result is incorrect.

### CODE REVIEW

**Comment by goto1134** [comment]
Yes, you are right. It is a known issue and you can help fixing it in #138

**Comment by goto1134** [comment]
This is not the only case, I mean

**Comment by goto1134** [comment]
There is a lot of simula places for different platforms and jnr configurations

**Comment by zhanhb** [comment]
Should type between integer type and floating type be available? I wrote a simple test

**Pull request closed without merging**
