### PR TITLE
PowerPC64 support

### PR DESCRIPTION
**Pull request by vitordelima**
This pull request adds support for the ppc64le architecture.

### CODE REVIEW

**Comment by leitao** [comment]
What is preventing this patches to be merged?

**Comment by lbianc** [comment]
@headius, @enebo - Can this PR be merged?

**Comment by headius** [comment]
Another PR that was simply missed...sorry folks. Merging today.

We will need to know whether this fixes #32 and #33 before releasing.

**Comment by ralphbellofatto** [comment]
I don't think this fixes 32 and 33.  

I based the branch i put together on this set of changes, expanded to also test out ppc64.

One problem i have found in testing on the ubuntu 14.10 release is that the openjdk missreports the os.arch, so this library does not have a prayer of fixing this.

On that system, i can load the IBM JDK and the test fails in the same manner as the ppc64 openJDK.

I created a fork and a branch to house these changes on github.
https://github.com/ralphbellofatto/jnr-ffi

something very deep involved in passing pointers to arrays is wrong with the code called by BufferMethodGenerator to generate the code to pass the pointer to an array.

**Pull request merged**
